// This file mimics the types that would be generated by Convex
// and adds documentation/sample data as requested.

export type Id<T extends string> = string & { __tableName: T };

// --------------------------------------------------------------------------
// Collection Interfaces
// --------------------------------------------------------------------------

/**
 * Represents a registered user in the system.
 */
export interface User {
  _id: Id<"users">;
  _creationTime: number;
  name: string;
  email: string;
  tokenIdentifier: string;
  targetLevel?: "HSK1" | "HSK2" | "HSK3" | "HSK4" | "HSK5" | "HSK6";
  dailyGoal?: number;
}

/**
 * A journal entry created by a user.
 * This is the primary source for "mining" sentences.
 */
export interface Journal {
  _id: Id<"journals">;
  _creationTime: number;
  userId: Id<"users">;
  title: string;
  content: string;
  createdAt: number;
  processed: boolean;
}

/**
 * A mined sentence.
 * Can be linked to a Journal or added manually.
 */
export interface Sentence {
  _id: Id<"sentences">;
  _creationTime: number;
  userId: Id<"users">;
  journalId?: Id<"journals">;
  original: string;
  pinyin: string;
  translation: string;
  difficulty?: "Easy" | "Medium" | "Hard";
  tags?: string[];
  source: "Journal" | "Manual" | "Import";
  audioUrl?: string;
  createdAt: number;
}

/**
 * Reference data for Grammar points.
 * Shared across all users (system data).
 */
export interface Grammar {
  _id: Id<"grammar">;
  _creationTime: number;
  point: string;
  level: string;
  explanation: string;
  structure: string;
  exampleSentences: {
    original: string;
    translation: string;
  }[];
}

/**
 * Reference data for Chinese Characters.
 * Shared across all users (system data).
 */
export interface Character {
  _id: Id<"characters">;
  _creationTime: number;
  char: string;
  pinyin: string[];
  meaning: string[];
  hskLevel: number;
  components?: string[];
  strokes?: number;
}

/**
 * Represents the state of an item in the User's Spaced Repetition System (SRS).
 * Links a User to a Sentence, Grammar, or Character.
 */
export interface ReviewItem {
  _id: Id<"user_review_deck">;
  _creationTime: number;
  userId: Id<"users">;
  type: "sentence" | "grammar" | "character";
  
  // Only one of these will be populated based on 'type'
  sentenceId?: Id<"sentences">;
  grammarId?: Id<"grammar">;
  characterId?: Id<"characters">;

  nextReview: number; // Unix timestamp
  interval: number; // Days
  easeFactor: number; // Float, usually starts at 2.5
  status: "new" | "learning" | "review" | "mastered";
  lastReview?: number; // Unix timestamp
}

// --------------------------------------------------------------------------
// Sample Data & Explanations
// --------------------------------------------------------------------------

export const SCHEMA_DOCS = {
  users: "Stores user identity and global learning settings.",
  journals: "Raw content input by users (e.g., diary entries, pasted articles) intended for processing.",
  sentences: "The atomic unit of learning. Extracted from journals or added manually.",
  grammar: "Static dictionary of grammar rules used for hinting and learning.",
  characters: "Static dictionary of character information.",
  user_review_deck: "The join table that tracks a user's progress on any learnable item (Sentence, Grammar, Character)."
};

export const SAMPLE_DATA = {
  users: {
    name: "Alex Chen",
    email: "alex@example.com",
    tokenIdentifier: "auth0|123456",
    targetLevel: "HSK4",
    dailyGoal: 5
  },
  journals: {
    userId: "users:123",
    title: "Trip to Beijing",
    content: "今天我去北京了。天气很好...",
    createdAt: 1715431200000,
    processed: true
  },
  sentences: {
    userId: "users:123",
    journalId: "journals:456",
    original: "今天天气很好。",
    pinyin: "Jīntiān tiānqì hěn hǎo.",
    translation: "The weather is very good today.",
    difficulty: "Easy",
    tags: ["travel", "weather"],
    source: "Journal",
    createdAt: 1715431500000
  },
  grammar: {
    point: "把 Structure",
    level: "HSK3",
    explanation: "Used to indicate how an action affects an object.",
    structure: "Subject + 把 + Object + Verb + Result",
    exampleSentences: [
      {
        original: "他把书放在桌子上了。",
        translation: "He put the book on the table."
      }
    ]
  },
  characters: {
    char: "好",
    pinyin: ["hǎo", "hào"],
    meaning: ["good", "well", "to like"],
    hskLevel: 1,
    components: ["女", "子"],
    strokes: 6
  },
  user_review_deck: {
    userId: "users:123",
    type: "sentence",
    sentenceId: "sentences:789",
    nextReview: 1715517600000,
    interval: 1,
    easeFactor: 2.5,
    status: "learning",
    lastReview: 1715431200000
  }
};