
/**
 * MOCK GENERATED FILE
 * In a real Convex app, this is generated by `npx convex dev`.
 * We mock it here to allow the UI to render without a running backend.
 */

export const api: any = {
  fetchSentences: {
    get: "fetchSentences:get",
  },
  submitJournal: {
    submit: "submitJournal:submit",
  },
  saveToSRS: {
    saveItem: "saveToSRS:saveItem",
  },
  generateAudio: {
    generate: "generateAudio:generate",
  },
};

export const internal: any = {
  submitJournal: {
    saveJournalData: "submitJournal:saveJournalData",
  },
  generateAudio: {
    getSentenceData: "generateAudio:getSentenceData",
    saveAudioUrl: "generateAudio:saveAudioUrl",
  },
};
