
/**
 * MOCK GENERATED FILE
 * In a real Convex app, this is generated by `npx convex dev`.
 */

import { GenericId } from "convex/values";

// Generic ID type that mimics Convex's ID
export type Id<TableName extends string> = string & { __tableName: TableName };

// Generic Document type
export type Doc<TableName extends string> = any;

export type TableNames = 
  | "users" 
  | "journals" 
  | "sentences" 
  | "grammar" 
  | "characters" 
  | "user_review_deck";
