
/**
 * MOCK GENERATED FILE
 * In a real Convex app, this is generated by `npx convex dev`.
 */

export const query = (args: any) => args as any;
export const mutation = (args: any) => args as any;
export const action = (args: any) => args as any;
export const internalQuery = (args: any) => args as any;
export const internalMutation = (args: any) => args as any;
export const internalAction = (args: any) => args as any;
